version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yapay_test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/yapay_test_db
      JWT_SECRET: your-secret-key
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm run start"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:4000/graphql
    depends_on:
      - backend

volumes:
  postgres_data: 